//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.cpp
//  @ Date : 11/03/2017
//  @ Author : 
//
//


#include "Person.h"

void Person::void walkAlong()
{

}

