//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.h
//  @ Date : 11/03/2017
//  @ Author : 
//
//


#if !defined(_PERSON_H)
#define _PERSON_H


class Person
{
public:
	void void walkAlong();
private:
	int int age;
	int bool hasgun;
};

#endif  //_PERSON_H
